//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveWhere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string UserId { get; set; }
        public int HotelId { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public double Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
